FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip
RUN apt-get install -y libsm6 libxext6 libxrender-dev

COPY ./ ./app
WORKDIR /app

# Make sure to expose all ports
EXPOSE 80 8001 8002 8003

RUN pip3 install -r requirements.txt

CMD python3 main.py
