FROM ubuntu:18.10


RUN apt-get update
RUN apt-get install -y python3 python3-dev python3-pip
RUN apt-get install -y libsm6 libxext6 libxrender-dev

COPY ./ ./app
WORKDIR ./app

RUN pip3 install -r requirements.txt

CMD python3 start.py
